USE `GSCOOKIEDB`;

ALTER TABLE SHIPMENT ADD ORDER_ID INT(11);

-- ALTER TABLE SHIPMENT 
--  ADD CONSTRAINT `FK-SHIPMENT-PRODUCT_ORDER`
--  FOREIGN KEY (`ORDER_ID` )
  -- REFERENCES `PR0DUCT_ORDER` (`ORDER_ID` )
 --  ON DELETE CASCADE
  -- ON UPDATE CASCADE;