USE GSCookieDB;

-- TRIGGERS --
DROP TRIGGER IF EXISTS CHECK_AMOUNT_ON_MONEY;

USE DELIMITER $$

CREATE TRIGGER CHECK_AMOUNT_ON_MONEY
BEFORE UPDATE ON `MONEY`
FOR EACH ROW BEGIN
	-- SELECT PRICE AS PRODUCT_PRICE INTO @PRODUCT_PRICE FROM PRODUCT WHERE `PRODUCT`.`PRODUCT_ID` = NEW.PRODUCT_ID;
    -- SELECT SCOUT_ID AS ORDERS_SCOUT_ID INTO @ORDERS_SCOUT_ID FROM PRODUCT_ORDER WHERE PRODUCT_ORDER.SCOUT_ID = NEW;
    -- SELECT QUANTITY AS ORDERS_QUANTITY INTO @ORDERS_QUANTITY FROM PRODUCT_ORDER WHERE PRODUCT_ORDER.QUANTITY = NEW.AMOUNT/PRODUCT_ORDER.QUANTITY;
    
    IF NEW.AMOUNT_RECEIVED > OLD.AMOUNT THEN 
		SIGNAL SQLSTATE 'HY000'
		SET MESSAGE_TEXT = 'AMOUNT RECEIVED CANNOT BE GREATER THAN COST AMOUNT OF THE PRODUCTS. PLEASE ENTER A SMALLER AMOUNT EQUAL TO OR LESS THAN AMOUNT!';
	END IF;
    
END;
