USE GSCookieDB;

SELECT *, (SELECT SUM(QUANTITY) FROM INVENTORY WHERE INVENTORY.TROOP_ID = TROOP.TROOP_ID) FROM TROOP;

SELECT PRODUCT_ID, NAME, (SELECT SUM(QUANTITY) FROM INVENTORY WHERE INVENTORY.PRODUCT_ID = PRODUCT.PRODUCT_ID) FROM PRODUCT ORDER BY PRODUCT.PRODUCT_ID;

-- NEW WAY
